CREATE TABLE task(
id INT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(200),
Datepost DATETIME


);
CREATE TABLE Notification(
   id INT PRIMARY KEY AUTO_INCREMENT,
   message VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);